### ISSUE TITLE
Support for other regions

### ISSUE THREAD

**Issue by modmusu** [AHpxChina/GenshinImactQuery#1]
Can you add support for other regions (America, Europe, Asia).
I would do this myself but I do not know how you got the server name ("server=cn_gf01") parameter in the API call.
I tried looking at outgoing API calls from the game client but could not find the server name for America.

**Comment by AHpxChina** [comment]
I have no idea about this, I got the API address by the mihoyo's app.
The way is, we can translate the Chinese name to other languages as text resources

**Comment by Womsxd** [comment]
https://api-takumi.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid= mihoyoUID
Please use this api to get serverid

**Comment by Womsxd** [comment]
> https://api-takumi.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid= mihoyoUID
> Please use this api to get serverid

No!!  This API is only applicable to mihoyo accounts in China!

**Comment by Womsxd** [comment]
Can you tell me your Genshin Imact UID and service?
I seem to have found the "region" of other servers.

**Comment by modmusu** [comment]
UID: 602377088
What do you mean by 'service'?

**Comment by Womsxd** [comment]
> UID: 602377088
> What do you mean by 'service'?

America|Europe|Aisa|TW,HK,MO

**Comment by modmusu** [comment]
America

**Comment by Womsxd** [comment]
region=os_usa America
region=os_euro Europe
region=os_asia Aisa
region=os_cht TW,HK,MO
But this API does not synchronize data from other servers
{"data":null,"message":"数据未同步","retcode":-1}
