### ISSUE TITLE
 Can't get info from api now

### ISSUE THREAD

**Issue by Lightczx** [AHpxChina/GenshinImactQuery#2]
always return :
{"data":null,"message":"请求异常","retcode":-401}
now.
I tried to change UA but doesn't help!
seems like mihoyo has changed the api invoke mean

**Comment by AHpxChina** [comment]
已确认这个api已经失效，解决方案是**爆破一个算法**

**Comment by AHpxChina** [comment]
现在项目已经可用，所以这个issue将被关闭
